// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_slice: dynamic(() => import("./AboutSlice")),
  rich_text: dynamic(() => import("./RichText")),
  why_neo_paisa: dynamic(() => import("./WhyNeoPaisa")),
};
